# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

use_frameworks!

target 'DataStructures' do

end

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'DataStructuresTests' do
    testing_pods
end
